# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
# busca automaticamente fontes de contrato do Etherscan
autofetch_sources: True
dotenv: .env
# setar um mnemonic para a development network
networks:
  default: goerli
  #https://docs.chain.link/vrf/v2/subscription/supported-networks/
  #Site utilizado para identificar as configurações das redes testes Ethereum

  #brownie networks add Ethereum sepolia host="https://sepolia.infura.io/v3/baa61b55443d4e4c9247fd72da8aaf40" chainid=11155111
  sepolia:
    vrf_coodinator: '0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625'
    link_token: '0x779877A7B0D9E8603169DdbD7836e478b4624789'
    keyhash: '0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c'

  #brownie networks add Ethereum goerli host="https://goerli.infura.io/v3/cffca94d5c0d41259420684bbfa2a647" chainid=5
  goerli:
    vrf_coordinator: '0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D'
    link_token: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
    keyhash: '0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15'
    fee: 250
  
settings:
  gas_limit: "100000000000"
wallets:
  from_key: ${PRIVATE_KEY}
